### ISSUE TITLE
Hola alejandro

### ISSUE THREAD

**Issue by jacobbalam** [alejandroscf/GSM-tracker#1]
Hola alejandro vi tu codigo y no se si aun este en funcionamiento, he solicitado el key de la api de mozilla y no me envian nada los de mozzila, ni si ni no.... saludos.

Jacob

**Comment by alejandroscf** [comment]
Buenas, 
A mi me respondieron de un día para otro, pero hace ya tres años de aquello, siempre puedes mandarles un email a mls-contact@mozilla.com, mientras tanto, para probar, puedes usar la clave de api "test" literalmente. En cualquier caso, con la API de openCellID debería funcionarte también la aplicación.
